source 'https://github.com/CocoaPods/Specs.git'

target 'MWPhotoBrowser_Example', :exclusive => true do
  pod "MWPhotoBrowser", :path => "../"
end

target 'MWPhotoBrowser_Tests', :exclusive => true do
  pod "MWPhotoBrowser", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
      pod 'SDWebImage',           '~> 4.2.2'

end
